USE Program
GO

CREATE OR ALTER PROCEDURE dbo.[SNG_TB_TIPO_PARAMETRO]
	@p_COD_TIPO_PARAMETRO  int
	, @p_MSG_RETORNO VARCHAR(MAX) = '' OUTPUT
	AS

BEGIN TRY

		DECLARE @Retorno INT = 0

SELECT a.COD_TIPO_PARAMETRO
     , a.DS_TIPO
     , a.DS_VALIDACAO_REGEX
     , a.FL_OBRIGATORIO_PADRAO
     , a.SIT_ATIVO
FROM Report.dbo.TB_TIPO_PARAMETRO a
WHERE a.COD_TIPO_PARAMETRO = @p_COD_TIPO_PARAMETRO

	RETURN @Retorno
END TRY
BEGIN
	CATCH
SELECT @p_MSG_RETORNO = 'Erro: [' + CAST(ERROR_NUMBER() AS VARCHAR) + '] - ' + ERROR_MESSAGE()
     , @Retorno		  = 50000
END CATCH

GO
