USE Program
GO

CREATE OR ALTER PROCEDURE dbo.[SNG_TB_RELATORIO_MODELO_PARAMETRO]
	@p_COD_PARAMETRO  int
	, @p_MSG_RETORNO VARCHAR(MAX) = '' OUTPUT
	AS

BEGIN TRY

		DECLARE @Retorno INT = 0

SELECT a.COD_PARAMETRO
     , a.COD_RELATORIO_MODELO
     , a.NM_PARAMETRO
     , a.DS_PARAMETRO
     , a.COD_TIPO_PARAMETRO
     , a.NR_ORDEM
     , a.FL_OBRIGATORIO
     , a.VL_PADRAO
     , a.DS_HELP
     , a.QT_MIN_CARACTERES
     , a.QT_MAX_CARACTERES
     , a.VL_MINIMO
     , a.VL_MAXIMO
     , a.FL_VISIVEL
     , a.FL_ATIVO
     , a.DT_CRIACAO
FROM Report.dbo.TB_RELATORIO_MODELO_PARAMETRO a
WHERE a.COD_PARAMETRO = @p_COD_PARAMETRO

	RETURN @Retorno
END TRY
BEGIN
	CATCH
SELECT @p_MSG_RETORNO = 'Erro: [' + CAST(ERROR_NUMBER() AS VARCHAR) + '] - ' + ERROR_MESSAGE()
     , @Retorno		  = 50000
END CATCH

GO
