USE Program
GO

CREATE OR ALTER PROCEDURE dbo.[SNG_TB_RELATORIO_MODELO_SAIDA]
	@p_COD_MODELO_SAIDA  int
	, @p_MSG_RETORNO VARCHAR(MAX) = '' OUTPUT
	AS

BEGIN TRY

		DECLARE @Retorno INT = 0

SELECT a.COD_MODELO_SAIDA
     , a.COD_RELATORIO_MODELO
     , a.NM_ABA_ARQUIVO
     , a.DS_SAIDA
     , a.NR_ORDEM
     , a.FL_ATIVO
     , a.DT_CRIACAO
FROM Report.dbo.TB_RELATORIO_MODELO_SAIDA a
WHERE a.COD_MODELO_SAIDA = @p_COD_MODELO_SAIDA

	RETURN @Retorno
END TRY
BEGIN
	CATCH
SELECT @p_MSG_RETORNO = 'Erro: [' + CAST(ERROR_NUMBER() AS VARCHAR) + '] - ' + ERROR_MESSAGE()
     , @Retorno		  = 50000
END CATCH

GO
