USE Program
GO

CREATE OR ALTER PROCEDURE dbo.[SNG_TB_STATUS_PROCESSAMENTO]
	@p_COD_STATUS_PROCESSAMENTO  int
	, @p_MSG_RETORNO VARCHAR(MAX) = '' OUTPUT
	AS

BEGIN TRY

		DECLARE @Retorno INT = 0

SELECT a.COD_STATUS_PROCESSAMENTO
     , a.DS_STATUS
     , a.SIT_ATIVO
     , a.DT_CRIACAO
FROM Report.dbo.TB_STATUS_PROCESSAMENTO a
WHERE a.COD_STATUS_PROCESSAMENTO = @p_COD_STATUS_PROCESSAMENTO

	RETURN @Retorno
END TRY
BEGIN
	CATCH
SELECT @p_MSG_RETORNO = 'Erro: [' + CAST(ERROR_NUMBER() AS VARCHAR) + '] - ' + ERROR_MESSAGE()
     , @Retorno		  = 50000
END CATCH

GO
