USE Program
GO

CREATE OR ALTER PROCEDURE dbo.[SNG_TB_RELATORIO_MODELO]
	@p_COD_RELATORIO_MODELO  int
	, @p_MSG_RETORNO VARCHAR(MAX) = '' OUTPUT
	AS

BEGIN TRY

		DECLARE @Retorno INT = 0

SELECT a.COD_RELATORIO_MODELO
     , a.NM_MODELO
     , a.DS_MODELO
     , a.NM_PROCEDURE
     , a.TP_ARQUIVO_PADRAO
     , a.COD_CATEGORIA
     , a.FL_ATIVO
     , a.QT_MAX_TENTATIVAS
     , a.QT_TIMEOUT_MINUTOS
     , a.DT_CRIACAO
     , a.COD_USUARIO_CRIACAO
     , a.DT_ALTERACAO
     , a.COD_USUARIO_ALTERACAO
FROM Report.dbo.TB_RELATORIO_MODELO a
WHERE a.COD_RELATORIO_MODELO = @p_COD_RELATORIO_MODELO

	RETURN @Retorno
END TRY
BEGIN
	CATCH
SELECT @p_MSG_RETORNO = 'Erro: [' + CAST(ERROR_NUMBER() AS VARCHAR) + '] - ' + ERROR_MESSAGE()
     , @Retorno		  = 50000
END CATCH

GO
