USE Program
GO

CREATE OR ALTER PROCEDURE dbo.[SNG_TB_RELATORIO_LOG]
	@p_COD_LOG  bigint
	, @p_MSG_RETORNO VARCHAR(MAX) = '' OUTPUT
	AS

BEGIN TRY

		DECLARE @Retorno INT = 0

SELECT a.COD_LOG
     , a.COD_RELATORIO_SOLICITACAO
     , a.DT_LOG
     , a.DS_EVENTO
     , a.DS_DETALHES
     , a.QT_TEMPO_EXECUCAO_MS
FROM Report.dbo.TB_RELATORIO_LOG a
WHERE a.COD_LOG = @p_COD_LOG

	RETURN @Retorno
END TRY
BEGIN
	CATCH
SELECT @p_MSG_RETORNO = 'Erro: [' + CAST(ERROR_NUMBER() AS VARCHAR) + '] - ' + ERROR_MESSAGE()
     , @Retorno		  = 50000
END CATCH

GO
