USE Program
GO

CREATE OR ALTER PROCEDURE dbo.[SNG_TB_RELATORIO_MODELO_PERMISSAO]
	@p_COD_PERMISSAO  int
	, @p_MSG_RETORNO VARCHAR(MAX) = '' OUTPUT
	AS

BEGIN TRY

		DECLARE @Retorno INT = 0

SELECT a.COD_PERMISSAO
     , a.COD_RELATORIO_MODELO
     , a.COD_USUARIO
     , a.COD_PERFIL
     , a.COD_DEPARTAMENTO
     , a.FL_PODE_EXECUTAR
     , a.FL_PODE_VISUALIZAR
     , a.FL_PODE_BAIXAR
     , a.DT_CRIACAO
FROM Report.dbo.TB_RELATORIO_MODELO_PERMISSAO a
WHERE a.COD_PERMISSAO = @p_COD_PERMISSAO

	RETURN @Retorno
END TRY
BEGIN
	CATCH
SELECT @p_MSG_RETORNO = 'Erro: [' + CAST(ERROR_NUMBER() AS VARCHAR) + '] - ' + ERROR_MESSAGE()
     , @Retorno		  = 50000
END CATCH

GO
