USE Program
GO

CREATE OR ALTER PROCEDURE dbo.[SNG_TB_RELATORIO_MODELO_DESTINO]
	@p_COD_MODELO_DESTINO  int
	, @p_MSG_RETORNO VARCHAR(MAX) = '' OUTPUT
	AS

BEGIN TRY

		DECLARE @Retorno INT = 0

SELECT a.COD_MODELO_DESTINO
     , a.COD_RELATORIO_MODELO
     , a.COD_DESTINO_TIPO
     , a.FL_NOTIFICAR_SOLICITANTE
     , a.DS_CONFIGURACAO_JSON
     , a.FL_ANEXAR_ARQUIVO
     , a.FL_ATIVO
FROM Report.dbo.TB_RELATORIO_MODELO_DESTINO a
WHERE a.COD_MODELO_DESTINO = @p_COD_MODELO_DESTINO

	RETURN @Retorno
END TRY
BEGIN
	CATCH
SELECT @p_MSG_RETORNO = 'Erro: [' + CAST(ERROR_NUMBER() AS VARCHAR) + '] - ' + ERROR_MESSAGE()
     , @Retorno		  = 50000
END CATCH

GO
