USE Program
GO

CREATE OR ALTER PROCEDURE dbo.[SNG_TB_RELATORIO_PARAMETRO_OPCAO]
	@p_COD_OPCAO  int
	, @p_MSG_RETORNO VARCHAR(MAX) = '' OUTPUT
	AS

BEGIN TRY

		DECLARE @Retorno INT = 0

SELECT a.COD_OPCAO
     , a.COD_PARAMETRO
     , a.VL_OPCAO
     , a.DS_OPCAO
     , a.NR_ORDEM
     , a.FL_ATIVO
FROM Report.dbo.TB_RELATORIO_PARAMETRO_OPCAO a
WHERE a.COD_OPCAO = @p_COD_OPCAO

	RETURN @Retorno
END TRY
BEGIN
	CATCH
SELECT @p_MSG_RETORNO = 'Erro: [' + CAST(ERROR_NUMBER() AS VARCHAR) + '] - ' + ERROR_MESSAGE()
     , @Retorno		  = 50000
END CATCH

GO
