USE Program
GO

CREATE OR ALTER PROCEDURE dbo.[SNG_TB_RELATORIO_SOLICITACAO]
	@p_COD_RELATORIO_SOLICITACAO  bigint
	, @p_MSG_RETORNO VARCHAR(MAX) = '' OUTPUT
	AS

BEGIN TRY

		DECLARE @Retorno INT = 0

SELECT a.COD_RELATORIO_SOLICITACAO
     , a.COD_RELATORIO_MODELO
     , a.COD_USUARIO
     , a.DS_PARAMETROS
     , a.COD_STATUS_PROCESSAMENTO
     , a.DT_CRIACAO
     , a.DT_INICIO_PROCESSAMENTO
     , a.DT_FIM_PROCESSAMENTO
     , a.URL_ARQUIVO
     , a.NM_ARQUIVO
     , a.TP_ARQUIVO
     , a.MSG_ERRO
     , a.QT_TENTATIVAS
     , a.FL_NOTIFICADO
     , a.COD_JOB_EXTERNO
     , a.QT_REGISTROS_GERADOS
     , a.QT_TAMANHO_ARQUIVO_KB
     , a.NM_PROCEDURE_AD_HOC
     , a.TP_ARQUIVO_SOLICITADO
     , a.DS_LAYOUT_SAIDA_JSON
FROM Report.dbo.TB_RELATORIO_SOLICITACAO a
WHERE a.COD_RELATORIO_SOLICITACAO = @p_COD_RELATORIO_SOLICITACAO

	RETURN @Retorno
END TRY
BEGIN
	CATCH
SELECT @p_MSG_RETORNO = 'Erro: [' + CAST(ERROR_NUMBER() AS VARCHAR) + '] - ' + ERROR_MESSAGE()
     , @Retorno		  = 50000
END CATCH

GO
