USE Program
GO

CREATE OR ALTER PROCEDURE dbo.[SNG_TB_RELATORIO_SOLICITACAO_DESTINO]
	@p_COD_SOLICITACAO_DESTINO  bigint
	, @p_MSG_RETORNO VARCHAR(MAX) = '' OUTPUT
	AS

BEGIN TRY

		DECLARE @Retorno INT = 0

SELECT a.COD_SOLICITACAO_DESTINO
     , a.COD_RELATORIO_SOLICITACAO
     , a.COD_DESTINO_TIPO
     , a.DS_CONFIGURACAO_JSON
     , a.FL_ANEXAR_ARQUIVO
     , a.COD_STATUS_PROCESSAMENTO
     , a.DT_ENVIO
     , a.MSG_ERRO
     , a.QT_TENTATIVAS
FROM Report.dbo.TB_RELATORIO_SOLICITACAO_DESTINO a
WHERE a.COD_SOLICITACAO_DESTINO = @p_COD_SOLICITACAO_DESTINO

	RETURN @Retorno
END TRY
BEGIN
	CATCH
SELECT @p_MSG_RETORNO = 'Erro: [' + CAST(ERROR_NUMBER() AS VARCHAR) + '] - ' + ERROR_MESSAGE()
     , @Retorno		  = 50000
END CATCH

GO
