USE Program
GO

CREATE OR ALTER PROCEDURE dbo.[SNG_TB_RELATORIO_DESTINO_TIPO]
	@p_COD_DESTINO_TIPO  int
	, @p_MSG_RETORNO VARCHAR(MAX) = '' OUTPUT
	AS

BEGIN TRY

		DECLARE @Retorno INT = 0

SELECT a.COD_DESTINO_TIPO
     , a.NM_TIPO
     , a.DS_TIPO
     , a.FL_ATIVO
FROM Report.dbo.TB_RELATORIO_DESTINO_TIPO a
WHERE a.COD_DESTINO_TIPO = @p_COD_DESTINO_TIPO

	RETURN @Retorno
END TRY
BEGIN
	CATCH
SELECT @p_MSG_RETORNO = 'Erro: [' + CAST(ERROR_NUMBER() AS VARCHAR) + '] - ' + ERROR_MESSAGE()
     , @Retorno		  = 50000
END CATCH

GO
