USE [Report]
GO
/****** Object:  Table [dbo].[TB_RELATORIO_CATEGORIA]    Script Date: 13/07/2025 13:48:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TB_RELATORIO_CATEGORIA](
	[COD_CATEGORIA] [int] IDENTITY(1,1) NOT NULL,
	[NM_CATEGORIA] [varchar](100) NOT NULL,
	[DS_CATEGORIA] [varchar](300) NULL,
	[FL_ATIVO] [bit] NULL,
	[NR_ORDEM] [int] NULL,
 CONSTRAINT [PK_TB_RELATORIO_CATEGORIA] PRIMARY KEY CLUSTERED 
(
	[COD_CATEGORIA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UQ_TB_RELATORIO_CATEGORIA_NM] UNIQUE NONCLUSTERED 
(
	[NM_CATEGORIA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TB_RELATORIO_DESTINO_TIPO]    Script Date: 13/07/2025 13:48:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TB_RELATORIO_DESTINO_TIPO](
	[COD_DESTINO_TIPO] [int] IDENTITY(1,1) NOT NULL,
	[NM_TIPO] [varchar](30) NOT NULL,
	[DS_TIPO] [varchar](200) NULL,
	[FL_ATIVO] [bit] NULL,
 CONSTRAINT [PK_TB_RELATORIO_DESTINO_TIPO] PRIMARY KEY CLUSTERED 
(
	[COD_DESTINO_TIPO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UQ_TB_RELATORIO_DESTINO_TIPO_NM] UNIQUE NONCLUSTERED 
(
	[NM_TIPO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TB_RELATORIO_LOG]    Script Date: 13/07/2025 13:48:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TB_RELATORIO_LOG](
	[COD_LOG] [bigint] IDENTITY(1,1) NOT NULL,
	[COD_RELATORIO_SOLICITACAO] [bigint] NOT NULL,
	[DT_LOG] [datetime2](7) NULL,
	[DS_EVENTO] [varchar](100) NOT NULL,
	[DS_DETALHES] [nvarchar](max) NULL,
	[QT_TEMPO_EXECUCAO_MS] [int] NULL,
 CONSTRAINT [PK_TB_RELATORIO_LOG] PRIMARY KEY CLUSTERED 
(
	[COD_LOG] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TB_RELATORIO_MODELO]    Script Date: 13/07/2025 13:48:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TB_RELATORIO_MODELO](
	[COD_RELATORIO_MODELO] [int] IDENTITY(1,1) NOT NULL,
	[NM_MODELO] [varchar](100) NOT NULL,
	[DS_MODELO] [varchar](500) NOT NULL,
	[NM_PROCEDURE] [varchar](100) NOT NULL,
	[TP_ARQUIVO_PADRAO] [varchar](10) NOT NULL,
	[COD_CATEGORIA] [int] NULL,
	[FL_ATIVO] [bit] NULL,
	[QT_MAX_TENTATIVAS] [int] NULL,
	[QT_TIMEOUT_MINUTOS] [int] NULL,
	[DT_CRIACAO] [datetime2](7) NULL,
	[COD_USUARIO_CRIACAO] [int] NOT NULL,
	[DT_ALTERACAO] [datetime2](7) NULL,
	[COD_USUARIO_ALTERACAO] [int] NULL,
 CONSTRAINT [PK_TB_RELATORIO_MODELO] PRIMARY KEY CLUSTERED 
(
	[COD_RELATORIO_MODELO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TB_RELATORIO_MODELO_DESTINO]    Script Date: 13/07/2025 13:48:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TB_RELATORIO_MODELO_DESTINO](
	[COD_MODELO_DESTINO] [int] IDENTITY(1,1) NOT NULL,
	[COD_RELATORIO_MODELO] [int] NOT NULL,
	[COD_DESTINO_TIPO] [int] NOT NULL,
	[FL_NOTIFICAR_SOLICITANTE] [bit] NULL,
	[DS_CONFIGURACAO_JSON] [nvarchar](max) NULL,
	[FL_ANEXAR_ARQUIVO] [bit] NULL,
	[FL_ATIVO] [bit] NULL,
 CONSTRAINT [PK_TB_RELATORIO_MODELO_DESTINO] PRIMARY KEY CLUSTERED 
(
	[COD_MODELO_DESTINO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UQ_TB_RELATORIO_MODELO_DESTINO_MODELO_TIPO] UNIQUE NONCLUSTERED 
(
	[COD_RELATORIO_MODELO] ASC,
	[COD_DESTINO_TIPO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TB_RELATORIO_MODELO_PARAMETRO]    Script Date: 13/07/2025 13:48:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TB_RELATORIO_MODELO_PARAMETRO](
	[COD_PARAMETRO] [int] IDENTITY(1,1) NOT NULL,
	[COD_RELATORIO_MODELO] [int] NOT NULL,
	[NM_PARAMETRO] [varchar](100) NOT NULL,
	[DS_PARAMETRO] [varchar](200) NOT NULL,
	[COD_TIPO_PARAMETRO] [int] NOT NULL,
	[NR_ORDEM] [int] NOT NULL,
	[FL_OBRIGATORIO] [bit] NULL,
	[VL_PADRAO] [varchar](500) NULL,
	[DS_HELP] [text] NULL,
	[QT_MIN_CARACTERES] [int] NULL,
	[QT_MAX_CARACTERES] [int] NULL,
	[VL_MINIMO] [decimal](18, 4) NULL,
	[VL_MAXIMO] [decimal](18, 4) NULL,
	[FL_VISIVEL] [bit] NULL,
	[FL_ATIVO] [bit] NULL,
	[DT_CRIACAO] [datetime2](7) NULL,
 CONSTRAINT [PK_TB_RELATORIO_MODELO_PARAMETRO] PRIMARY KEY CLUSTERED 
(
	[COD_PARAMETRO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TB_RELATORIO_MODELO_PERMISSAO]    Script Date: 13/07/2025 13:48:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TB_RELATORIO_MODELO_PERMISSAO](
	[COD_PERMISSAO] [int] IDENTITY(1,1) NOT NULL,
	[COD_RELATORIO_MODELO] [int] NOT NULL,
	[COD_USUARIO] [int] NULL,
	[COD_PERFIL] [int] NULL,
	[COD_DEPARTAMENTO] [int] NULL,
	[FL_PODE_EXECUTAR] [bit] NULL,
	[FL_PODE_VISUALIZAR] [bit] NULL,
	[FL_PODE_BAIXAR] [bit] NULL,
	[DT_CRIACAO] [datetime2](7) NULL,
 CONSTRAINT [PK_TB_RELATORIO_MODELO_PERMISSAO] PRIMARY KEY CLUSTERED 
(
	[COD_PERMISSAO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TB_RELATORIO_MODELO_SAIDA]    Script Date: 13/07/2025 13:48:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TB_RELATORIO_MODELO_SAIDA](
	[COD_MODELO_SAIDA] [int] IDENTITY(1,1) NOT NULL,
	[COD_RELATORIO_MODELO] [int] NOT NULL,
	[NM_ABA_ARQUIVO] [varchar](100) NOT NULL,
	[DS_SAIDA] [varchar](500) NULL,
	[NR_ORDEM] [int] NOT NULL,
	[FL_ATIVO] [bit] NULL,
	[DT_CRIACAO] [datetime2](7) NULL,
 CONSTRAINT [PK_TB_RELATORIO_MODELO_SAIDA] PRIMARY KEY CLUSTERED 
(
	[COD_MODELO_SAIDA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TB_RELATORIO_PARAMETRO_OPCAO]    Script Date: 13/07/2025 13:48:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TB_RELATORIO_PARAMETRO_OPCAO](
	[COD_OPCAO] [int] IDENTITY(1,1) NOT NULL,
	[COD_PARAMETRO] [int] NOT NULL,
	[VL_OPCAO] [varchar](100) NOT NULL,
	[DS_OPCAO] [varchar](200) NOT NULL,
	[NR_ORDEM] [int] NULL,
	[FL_ATIVO] [bit] NULL,
 CONSTRAINT [PK_TB_RELATORIO_PARAMETRO_OPCAO] PRIMARY KEY CLUSTERED 
(
	[COD_OPCAO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TB_RELATORIO_SOLICITACAO]    Script Date: 13/07/2025 13:48:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TB_RELATORIO_SOLICITACAO](
	[COD_RELATORIO_SOLICITACAO] [bigint] IDENTITY(1,1) NOT NULL,
	[COD_RELATORIO_MODELO] [int] NULL,
	[COD_USUARIO] [int] NOT NULL,
	[DS_PARAMETROS] [nvarchar](max) NULL,
	[COD_STATUS_PROCESSAMENTO] [int] NOT NULL,
	[DT_CRIACAO] [datetime2](7) NULL,
	[DT_INICIO_PROCESSAMENTO] [datetime2](7) NULL,
	[DT_FIM_PROCESSAMENTO] [datetime2](7) NULL,
	[URL_ARQUIVO] [varchar](500) NULL,
	[NM_ARQUIVO] [varchar](255) NULL,
	[TP_ARQUIVO] [varchar](10) NULL,
	[MSG_ERRO] [nvarchar](max) NULL,
	[QT_TENTATIVAS] [int] NULL,
	[FL_NOTIFICADO] [bit] NULL,
	[COD_JOB_EXTERNO] [varchar](100) NULL,
	[QT_REGISTROS_GERADOS] [int] NULL,
	[QT_TAMANHO_ARQUIVO_KB] [int] NULL,
	[NM_PROCEDURE_AD_HOC] [varchar](100) NULL,
	[TP_ARQUIVO_SOLICITADO] [varchar](10) NULL,
	[DS_LAYOUT_SAIDA_JSON] [nvarchar](max) NULL,
 CONSTRAINT [PK_TB_RELATORIO_SOLICITACAO] PRIMARY KEY CLUSTERED 
(
	[COD_RELATORIO_SOLICITACAO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TB_RELATORIO_SOLICITACAO_DESTINO]    Script Date: 13/07/2025 13:48:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TB_RELATORIO_SOLICITACAO_DESTINO](
	[COD_SOLICITACAO_DESTINO] [bigint] IDENTITY(1,1) NOT NULL,
	[COD_RELATORIO_SOLICITACAO] [bigint] NOT NULL,
	[COD_DESTINO_TIPO] [int] NOT NULL,
	[DS_CONFIGURACAO_JSON] [nvarchar](max) NOT NULL,
	[FL_ANEXAR_ARQUIVO] [bit] NULL,
	[COD_STATUS_PROCESSAMENTO] [int] NOT NULL,
	[DT_ENVIO] [datetime2](7) NULL,
	[MSG_ERRO] [nvarchar](max) NULL,
	[QT_TENTATIVAS] [int] NULL,
 CONSTRAINT [PK_TB_RELATORIO_SOLICITACAO_DESTINO] PRIMARY KEY CLUSTERED 
(
	[COD_SOLICITACAO_DESTINO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TB_STATUS_PROCESSAMENTO]    Script Date: 13/07/2025 13:48:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TB_STATUS_PROCESSAMENTO](
	[COD_STATUS_PROCESSAMENTO] [int] NOT NULL,
	[DS_STATUS] [varchar](50) NOT NULL,
	[SIT_ATIVO] [bit] NULL,
	[DT_CRIACAO] [datetime2](7) NULL,
PRIMARY KEY CLUSTERED 
(
	[COD_STATUS_PROCESSAMENTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UQ_TB_STATUS_PROCESSAMENTO_DS] UNIQUE NONCLUSTERED 
(
	[DS_STATUS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TB_TIPO_PARAMETRO]    Script Date: 13/07/2025 13:48:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TB_TIPO_PARAMETRO](
	[COD_TIPO_PARAMETRO] [int] IDENTITY(1,1) NOT NULL,
	[DS_TIPO] [varchar](30) NOT NULL,
	[DS_VALIDACAO_REGEX] [varchar](500) NULL,
	[FL_OBRIGATORIO_PADRAO] [bit] NULL,
	[SIT_ATIVO] [bit] NULL,
 CONSTRAINT [PK_TB_TIPO_PARAMETRO] PRIMARY KEY CLUSTERED 
(
	[COD_TIPO_PARAMETRO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UQ_TB_TIPO_PARAMETRO_DS] UNIQUE NONCLUSTERED 
(
	[DS_TIPO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TB_RELATORIO_CATEGORIA] ADD  DEFAULT ((1)) FOR [FL_ATIVO]
GO
ALTER TABLE [dbo].[TB_RELATORIO_CATEGORIA] ADD  DEFAULT ((0)) FOR [NR_ORDEM]
GO
ALTER TABLE [dbo].[TB_RELATORIO_DESTINO_TIPO] ADD  DEFAULT ((1)) FOR [FL_ATIVO]
GO
ALTER TABLE [dbo].[TB_RELATORIO_LOG] ADD  DEFAULT (getdate()) FOR [DT_LOG]
GO
ALTER TABLE [dbo].[TB_RELATORIO_MODELO] ADD  DEFAULT ((1)) FOR [FL_ATIVO]
GO
ALTER TABLE [dbo].[TB_RELATORIO_MODELO] ADD  DEFAULT ((3)) FOR [QT_MAX_TENTATIVAS]
GO
ALTER TABLE [dbo].[TB_RELATORIO_MODELO] ADD  DEFAULT ((30)) FOR [QT_TIMEOUT_MINUTOS]
GO
ALTER TABLE [dbo].[TB_RELATORIO_MODELO] ADD  DEFAULT (getdate()) FOR [DT_CRIACAO]
GO
ALTER TABLE [dbo].[TB_RELATORIO_MODELO_DESTINO] ADD  DEFAULT ((0)) FOR [FL_NOTIFICAR_SOLICITANTE]
GO
ALTER TABLE [dbo].[TB_RELATORIO_MODELO_DESTINO] ADD  DEFAULT ((1)) FOR [FL_ANEXAR_ARQUIVO]
GO
ALTER TABLE [dbo].[TB_RELATORIO_MODELO_DESTINO] ADD  DEFAULT ((1)) FOR [FL_ATIVO]
GO
ALTER TABLE [dbo].[TB_RELATORIO_MODELO_PARAMETRO] ADD  DEFAULT ((0)) FOR [NR_ORDEM]
GO
ALTER TABLE [dbo].[TB_RELATORIO_MODELO_PARAMETRO] ADD  DEFAULT ((0)) FOR [FL_OBRIGATORIO]
GO
ALTER TABLE [dbo].[TB_RELATORIO_MODELO_PARAMETRO] ADD  DEFAULT ((1)) FOR [FL_VISIVEL]
GO
ALTER TABLE [dbo].[TB_RELATORIO_MODELO_PARAMETRO] ADD  DEFAULT ((1)) FOR [FL_ATIVO]
GO
ALTER TABLE [dbo].[TB_RELATORIO_MODELO_PARAMETRO] ADD  DEFAULT (getdate()) FOR [DT_CRIACAO]
GO
ALTER TABLE [dbo].[TB_RELATORIO_MODELO_PERMISSAO] ADD  DEFAULT ((1)) FOR [FL_PODE_EXECUTAR]
GO
ALTER TABLE [dbo].[TB_RELATORIO_MODELO_PERMISSAO] ADD  DEFAULT ((1)) FOR [FL_PODE_VISUALIZAR]
GO
ALTER TABLE [dbo].[TB_RELATORIO_MODELO_PERMISSAO] ADD  DEFAULT ((1)) FOR [FL_PODE_BAIXAR]
GO
ALTER TABLE [dbo].[TB_RELATORIO_MODELO_PERMISSAO] ADD  DEFAULT (getdate()) FOR [DT_CRIACAO]
GO
ALTER TABLE [dbo].[TB_RELATORIO_MODELO_SAIDA] ADD  DEFAULT ((1)) FOR [FL_ATIVO]
GO
ALTER TABLE [dbo].[TB_RELATORIO_MODELO_SAIDA] ADD  DEFAULT (getdate()) FOR [DT_CRIACAO]
GO
ALTER TABLE [dbo].[TB_RELATORIO_PARAMETRO_OPCAO] ADD  DEFAULT ((0)) FOR [NR_ORDEM]
GO
ALTER TABLE [dbo].[TB_RELATORIO_PARAMETRO_OPCAO] ADD  DEFAULT ((1)) FOR [FL_ATIVO]
GO
ALTER TABLE [dbo].[TB_RELATORIO_SOLICITACAO] ADD  DEFAULT ((1)) FOR [COD_STATUS_PROCESSAMENTO]
GO
ALTER TABLE [dbo].[TB_RELATORIO_SOLICITACAO] ADD  DEFAULT (getdate()) FOR [DT_CRIACAO]
GO
ALTER TABLE [dbo].[TB_RELATORIO_SOLICITACAO] ADD  DEFAULT ((0)) FOR [QT_TENTATIVAS]
GO
ALTER TABLE [dbo].[TB_RELATORIO_SOLICITACAO] ADD  DEFAULT ((0)) FOR [FL_NOTIFICADO]
GO
ALTER TABLE [dbo].[TB_RELATORIO_SOLICITACAO_DESTINO] ADD  DEFAULT ((1)) FOR [FL_ANEXAR_ARQUIVO]
GO
ALTER TABLE [dbo].[TB_RELATORIO_SOLICITACAO_DESTINO] ADD  DEFAULT ((1)) FOR [COD_STATUS_PROCESSAMENTO]
GO
ALTER TABLE [dbo].[TB_RELATORIO_SOLICITACAO_DESTINO] ADD  DEFAULT ((0)) FOR [QT_TENTATIVAS]
GO
ALTER TABLE [dbo].[TB_STATUS_PROCESSAMENTO] ADD  DEFAULT ((1)) FOR [SIT_ATIVO]
GO
ALTER TABLE [dbo].[TB_STATUS_PROCESSAMENTO] ADD  DEFAULT (getdate()) FOR [DT_CRIACAO]
GO
ALTER TABLE [dbo].[TB_TIPO_PARAMETRO] ADD  DEFAULT ((0)) FOR [FL_OBRIGATORIO_PADRAO]
GO
ALTER TABLE [dbo].[TB_TIPO_PARAMETRO] ADD  DEFAULT ((1)) FOR [SIT_ATIVO]
GO
ALTER TABLE [dbo].[TB_RELATORIO_LOG]  WITH CHECK ADD  CONSTRAINT [FK_TB_RELATORIO_LOG_TB_RELATORIO_SOLICITACAO] FOREIGN KEY([COD_RELATORIO_SOLICITACAO])
REFERENCES [dbo].[TB_RELATORIO_SOLICITACAO] ([COD_RELATORIO_SOLICITACAO])
GO
ALTER TABLE [dbo].[TB_RELATORIO_LOG] CHECK CONSTRAINT [FK_TB_RELATORIO_LOG_TB_RELATORIO_SOLICITACAO]
GO
ALTER TABLE [dbo].[TB_RELATORIO_MODELO]  WITH CHECK ADD  CONSTRAINT [FK_TB_RELATORIO_MODELO_TB_RELATORIO_CATEGORIA] FOREIGN KEY([COD_CATEGORIA])
REFERENCES [dbo].[TB_RELATORIO_CATEGORIA] ([COD_CATEGORIA])
GO
ALTER TABLE [dbo].[TB_RELATORIO_MODELO] CHECK CONSTRAINT [FK_TB_RELATORIO_MODELO_TB_RELATORIO_CATEGORIA]
GO
ALTER TABLE [dbo].[TB_RELATORIO_MODELO_DESTINO]  WITH CHECK ADD  CONSTRAINT [FK_TB_RELATORIO_MODELO_DESTINO_TB_RELATORIO_DESTINO_TIPO] FOREIGN KEY([COD_DESTINO_TIPO])
REFERENCES [dbo].[TB_RELATORIO_DESTINO_TIPO] ([COD_DESTINO_TIPO])
GO
ALTER TABLE [dbo].[TB_RELATORIO_MODELO_DESTINO] CHECK CONSTRAINT [FK_TB_RELATORIO_MODELO_DESTINO_TB_RELATORIO_DESTINO_TIPO]
GO
ALTER TABLE [dbo].[TB_RELATORIO_MODELO_DESTINO]  WITH CHECK ADD  CONSTRAINT [FK_TB_RELATORIO_MODELO_DESTINO_TB_RELATORIO_MODELO] FOREIGN KEY([COD_RELATORIO_MODELO])
REFERENCES [dbo].[TB_RELATORIO_MODELO] ([COD_RELATORIO_MODELO])
GO
ALTER TABLE [dbo].[TB_RELATORIO_MODELO_DESTINO] CHECK CONSTRAINT [FK_TB_RELATORIO_MODELO_DESTINO_TB_RELATORIO_MODELO]
GO
ALTER TABLE [dbo].[TB_RELATORIO_MODELO_PARAMETRO]  WITH CHECK ADD  CONSTRAINT [FK_TB_RELATORIO_MODELO_PARAMETRO_TB_RELATORIO_MODELO] FOREIGN KEY([COD_RELATORIO_MODELO])
REFERENCES [dbo].[TB_RELATORIO_MODELO] ([COD_RELATORIO_MODELO])
GO
ALTER TABLE [dbo].[TB_RELATORIO_MODELO_PARAMETRO] CHECK CONSTRAINT [FK_TB_RELATORIO_MODELO_PARAMETRO_TB_RELATORIO_MODELO]
GO
ALTER TABLE [dbo].[TB_RELATORIO_MODELO_PARAMETRO]  WITH CHECK ADD  CONSTRAINT [FK_TB_RELATORIO_MODELO_PARAMETRO_TB_TIPO_PARAMETRO] FOREIGN KEY([COD_TIPO_PARAMETRO])
REFERENCES [dbo].[TB_TIPO_PARAMETRO] ([COD_TIPO_PARAMETRO])
GO
ALTER TABLE [dbo].[TB_RELATORIO_MODELO_PARAMETRO] CHECK CONSTRAINT [FK_TB_RELATORIO_MODELO_PARAMETRO_TB_TIPO_PARAMETRO]
GO
ALTER TABLE [dbo].[TB_RELATORIO_MODELO_PERMISSAO]  WITH CHECK ADD  CONSTRAINT [FK_TB_RELATORIO_MODELO_PERMISSAO_TB_RELATORIO_MODELO] FOREIGN KEY([COD_RELATORIO_MODELO])
REFERENCES [dbo].[TB_RELATORIO_MODELO] ([COD_RELATORIO_MODELO])
GO
ALTER TABLE [dbo].[TB_RELATORIO_MODELO_PERMISSAO] CHECK CONSTRAINT [FK_TB_RELATORIO_MODELO_PERMISSAO_TB_RELATORIO_MODELO]
GO
ALTER TABLE [dbo].[TB_RELATORIO_MODELO_SAIDA]  WITH CHECK ADD  CONSTRAINT [FK_TB_RELATORIO_MODELO_SAIDA_TB_RELATORIO_MODELO] FOREIGN KEY([COD_RELATORIO_MODELO])
REFERENCES [dbo].[TB_RELATORIO_MODELO] ([COD_RELATORIO_MODELO])
GO
ALTER TABLE [dbo].[TB_RELATORIO_MODELO_SAIDA] CHECK CONSTRAINT [FK_TB_RELATORIO_MODELO_SAIDA_TB_RELATORIO_MODELO]
GO
ALTER TABLE [dbo].[TB_RELATORIO_PARAMETRO_OPCAO]  WITH CHECK ADD  CONSTRAINT [FK_TB_RELATORIO_PARAMETRO_OPCAO_TB_RELATORIO_MODELO_PARAMETRO] FOREIGN KEY([COD_PARAMETRO])
REFERENCES [dbo].[TB_RELATORIO_MODELO_PARAMETRO] ([COD_PARAMETRO])
GO
ALTER TABLE [dbo].[TB_RELATORIO_PARAMETRO_OPCAO] CHECK CONSTRAINT [FK_TB_RELATORIO_PARAMETRO_OPCAO_TB_RELATORIO_MODELO_PARAMETRO]
GO
ALTER TABLE [dbo].[TB_RELATORIO_SOLICITACAO]  WITH CHECK ADD  CONSTRAINT [FK_TB_RELATORIO_SOLICITACAO_TB_RELATORIO_MODELO] FOREIGN KEY([COD_RELATORIO_MODELO])
REFERENCES [dbo].[TB_RELATORIO_MODELO] ([COD_RELATORIO_MODELO])
GO
ALTER TABLE [dbo].[TB_RELATORIO_SOLICITACAO] CHECK CONSTRAINT [FK_TB_RELATORIO_SOLICITACAO_TB_RELATORIO_MODELO]
GO
ALTER TABLE [dbo].[TB_RELATORIO_SOLICITACAO]  WITH CHECK ADD  CONSTRAINT [FK_TB_RELATORIO_SOLICITACAO_TB_STATUS_PROCESSAMENTO] FOREIGN KEY([COD_STATUS_PROCESSAMENTO])
REFERENCES [dbo].[TB_STATUS_PROCESSAMENTO] ([COD_STATUS_PROCESSAMENTO])
GO
ALTER TABLE [dbo].[TB_RELATORIO_SOLICITACAO] CHECK CONSTRAINT [FK_TB_RELATORIO_SOLICITACAO_TB_STATUS_PROCESSAMENTO]
GO
ALTER TABLE [dbo].[TB_RELATORIO_SOLICITACAO_DESTINO]  WITH CHECK ADD  CONSTRAINT [FK_TB_RELATORIO_SOLICITACAO_DESTINO_TB_RELATORIO_DESTINO_TIPO] FOREIGN KEY([COD_DESTINO_TIPO])
REFERENCES [dbo].[TB_RELATORIO_DESTINO_TIPO] ([COD_DESTINO_TIPO])
GO
ALTER TABLE [dbo].[TB_RELATORIO_SOLICITACAO_DESTINO] CHECK CONSTRAINT [FK_TB_RELATORIO_SOLICITACAO_DESTINO_TB_RELATORIO_DESTINO_TIPO]
GO
ALTER TABLE [dbo].[TB_RELATORIO_SOLICITACAO_DESTINO]  WITH CHECK ADD  CONSTRAINT [FK_TB_RELATORIO_SOLICITACAO_DESTINO_TB_RELATORIO_SOLICITACAO] FOREIGN KEY([COD_RELATORIO_SOLICITACAO])
REFERENCES [dbo].[TB_RELATORIO_SOLICITACAO] ([COD_RELATORIO_SOLICITACAO])
GO
ALTER TABLE [dbo].[TB_RELATORIO_SOLICITACAO_DESTINO] CHECK CONSTRAINT [FK_TB_RELATORIO_SOLICITACAO_DESTINO_TB_RELATORIO_SOLICITACAO]
GO
ALTER TABLE [dbo].[TB_RELATORIO_SOLICITACAO_DESTINO]  WITH CHECK ADD  CONSTRAINT [FK_TB_RELATORIO_SOLICITACAO_DESTINO_TB_STATUS_PROCESSAMENTO] FOREIGN KEY([COD_STATUS_PROCESSAMENTO])
REFERENCES [dbo].[TB_STATUS_PROCESSAMENTO] ([COD_STATUS_PROCESSAMENTO])
GO
ALTER TABLE [dbo].[TB_RELATORIO_SOLICITACAO_DESTINO] CHECK CONSTRAINT [FK_TB_RELATORIO_SOLICITACAO_DESTINO_TB_STATUS_PROCESSAMENTO]
GO
ALTER TABLE [dbo].[TB_RELATORIO_MODELO]  WITH CHECK ADD  CONSTRAINT [CK_TB_RELATORIO_MODELO_TP_ARQUIVO] CHECK  (([TP_ARQUIVO_PADRAO]='CSV' OR [TP_ARQUIVO_PADRAO]='XLSX' OR [TP_ARQUIVO_PADRAO]='PDF'))
GO
ALTER TABLE [dbo].[TB_RELATORIO_MODELO] CHECK CONSTRAINT [CK_TB_RELATORIO_MODELO_TP_ARQUIVO]
GO
ALTER TABLE [dbo].[TB_RELATORIO_SOLICITACAO]  WITH CHECK ADD  CONSTRAINT [CK_TB_RELATORIO_SOLICITACAO_MODELO_OU_ADHOC] CHECK  (([COD_RELATORIO_MODELO] IS NOT NULL AND [NM_PROCEDURE_AD_HOC] IS NULL OR [COD_RELATORIO_MODELO] IS NULL AND [NM_PROCEDURE_AD_HOC] IS NOT NULL))
GO
ALTER TABLE [dbo].[TB_RELATORIO_SOLICITACAO] CHECK CONSTRAINT [CK_TB_RELATORIO_SOLICITACAO_MODELO_OU_ADHOC]
GO
